version: "3"

services: 
  nginx:
    image: nginx:latest
    volumes:
      - ./:/var/www/
      - ./_docker/nginx/conf.d/:/etc/nginx/conf.d/
    ports:
      - "8876:80"
    depends_on:
      - app
    container_name: pastebin_nginx
    
  app:
   build:
    context: .
    dockerfile: _docker/app/Dockerfile
   volumes:
     - ./:/var/www/
   user: 1000:1000
   depends_on: 
     - db
   container_name: pastebin_app

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - "6432:5432"
    container_name: pastebin_db
    volumes:
       - db:/var/lib/postgresql/data

volumes:
   db:
     driver: local